

(1)


In [1]:
tinggi = [180, 215, 210, 210, 188, 176, 209, 200] # dalam cm 

# Import numpy dengan alias np
import numpy as np

# Buat numpy array dengan list tinggi beri nama variabel np_tinggi
np_tinggi = np.array(tinggi)


# Print tipe data np_baseball
print(type(np_tinggi))

<class 'numpy.ndarray'>




(2)


In [3]:
# Buat np_tinggi menjadi dalam satuan meter
np_tinggi = np_tinggi/100

# print np_tinggi
print(np_tinggi)

[1.8  2.15 2.1  2.1  1.88 1.76 2.09 2.  ]




(3)


In [5]:
berat = [88.5, 100, 98, 101, 78.3, 65.3, 109, 110]

# Buatlah numpy array dari list berat dan simpan dalam np_berat
np_berat = np.array(berat)

# hitung bmi dari berat dan tinggi simpan ke dalam variabel bmi
bmi = np_berat / np_tinggi ** 2
print(bmi)

[27.31481481 21.63331531 22.22222222 22.90249433 22.15368945 21.08083678
 24.95364117 27.5       ]




(4)


In [6]:
# Buatalah numpy array boolean dengan denga operator > untuk mencari bmi yang lebih besar dari 23
# Simpan dalam variabel bmi_tinggi
bmi_tinggi = bmi >23

# Partisi numpy array bmi dengan menggunkan bmi_tinggi untuk mencari bmi yang hanya lebih besar dari 23
bmi = np.array(bmi)[bmi_tinggi]
print(bmi)

[27.31481481 24.95364117 27.5       ]




(5)

    np.array([True, 1, 2]) + np.array([3, 4, False])
    Manakah pilihan di bawah ini yang memilik hasil sama seperti di atas?
    A. np.array([True, 1, 2, 3, 4, False])
    B. np.array([4, 3, 0]) + np.array([0, 2, 2])
    C. np.array([1, 1, 2]) + np.array([3, 4, -1])
    D. np.array([0, 1, 2, 3, 4, 5])



In [7]:


dem = np.array([True, 1, 2]) + np.array([3, 4, False])
print(dem)

[4 5 2]


In [8]:


dem = np.array([True, 1, 2, 3. 4. False]) 
print(dem)

SyntaxError: invalid syntax (<ipython-input-8-4889f05d22a2>, line 1)

In [10]:
dem = np.array([4, 3, 0]) + np.array([0, 2, 2])
print(dem)

[4 5 2]


In [11]:
dem = np.array([1, 1, 2]) + np.array([3, 4, -1])
print(dem)

[4 5 1]


In [13]:
dem = np.array([0, 1, 2, 3, 4, 5])
print(dem)

[0 1 2 3 4 5]


In [14]:
#B



(6)
subsetting 1D numpy array


In [15]:
# print hasil np_berat yang melik index terakhir
print(np_berat[-1])

# print 5 elemen terakhir dari np_tinggi
print(np_tinggi[-5:])

110.0
[2.1  1.88 1.76 2.09 2.  ]



2D Numpy Array¶


(7)


In [16]:
pemain_basket = [[180, 78.4],
                [215, 102.7],
                [210, 98.5],
                [188, 75.2]]

# Buatlah 2D array dari pemain_basket simpan dalam variabel basket_2d
basket_2d = np.array([[180, 78.4],[215, 102.7],[210, 98.5],[188, 75.2]])

# print tipe dari basket_2d

print(type(basket_2d))
# print basket_2d
print(basket_2d)

# print dimensi dari basket_2d dengan basket_2d.shape
print(basket_2d.shape)

<class 'numpy.ndarray'>
[[180.   78.4]
 [215.  102.7]
 [210.   98.5]
 [188.   75.2]]
(4, 2)




(8)


In [17]:
# Gunakan slicing untuk untuk mengambil hanya kolom pertama dari basket_2d
basket_2d[:,0]

# Gunakan slicing untuk mendapatkan 2 baris terakhir dan hanya kolom kedua dari basket_2d
basket_2d[2:,1]

array([98.5, 75.2])



(9) Coba eksekusi hasil di bawah ini apa hasilnya?


In [18]:
np_mat = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])
print(np_mat * 2)
print(np_mat + np.array([10, 10]))
print(np_mat + np_mat)

[[ 2  4]
 [ 6  8]
 [10 12]]
[[11 12]
 [13 14]
 [15 16]]
[[ 2  4]
 [ 6  8]
 [10 12]]


In [20]:
# Print dengan tambahkan berat dari basket_2d (kolom kedua) dengan 5 
print(np.add(basket_2d[:,1],5))

# Print dengan mengubah tinggi basket_2d (kolom pertama) yang awalnya satuannya cm menjadi m
print(np.divide(basket_2d[:,0],100))

[ 83.4 107.7 103.5  80.2]
[1.8  2.15 2.1  1.88]



Statisika dasar dengan menggunakan NumPy

(10)


In [21]:
# Berapakah mean dari np_tinggi? Kemudian print
print(np.mean(np_tinggi))

# Berapakah median dari np_tinggi? Kemudian print
print(np.median(np_tinggi))

1.9849999999999999
2.045




(11)


In [24]:
# Print tinggi dari basket_2d (kolom pertama)
rata_rata = np.mean(basket_2d[:,0])
print("Rata - Rata: " + str(rata_rata) )

# Print median dari tinggi basket_2d
med = np.median(basket_2d)
print("Median: " + str(med))

# Print standar deviasi dari basket_2d
stddev = np.std(basket_2d)
print("Standard Deviation: " + str(stddev))

# Print korelasi antara kolom pertama dengan kedua dari basket_2d
korelasi = np.corrcoef(basket_2d[:,[0,1]])
print("Korealasi: " + str(korelasi))

Rata - Rata: 198.25
Median: 141.35
Standard Deviation: 56.390973346804365
Korealasi: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
